
# Trigger the workflow manually
on:
  workflow_dispatch:

# Jobs to be executed
jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    
    steps:
      # Step 1: Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
      
      # Step 2: Install Salesforce Scanner
      - name: 'Install Salesforce Scanner'
        run: sfdx plugins:install @salesforce/sfdx-scanner

      # Step 3: Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          ref: master
      
      # Step 4: List items
      - name: 'List items in deployPackage'
        run: ls 'deployPackage'
      
      # Step 5: Set the instanceUrl config value
      - name: 'Set the instanceUrl config value'
        run: sfdx config:set instanceUrl=https://resourceful-goat-tmk2o9-dev-ed.trailblaze.my.salesforce.com
      
      # Step 6: Authorize DevOps User
      - name: 'Authorize Devops User'
        run: sfdx force:auth:jwt:grant -i "3MVG9PwZx9R6_UrffBFrptFbT3ajGmCNzbCex4_eHH1wqP6kgVUA5Q072jRUnfCIdxrYdMkGkMHGJYQNhMgSS" -f JWT/server.key -a FABAL --username feriel.abalache@resourceful-goat-tmk2o9.com

      # Step 7: Run Salesforce Scanner for Code Validation
      - name: 'Run Salesforce Code Validation'
        run: |
          mkdir reports
          sfdx scanner:run --target deployPackage --format html --outfile reports/scan-report.html
          echo "Code validation completed. Report saved at reports/scan-report.html"
      
      # Step 8: Deploy the release to the Integration org
      - name: 'Deploy the release to UAT org'
        run: sfdx force:source:deploy -x "deployPackage/package.xml" -u feriel.abalache@resourceful-goat-tmk2o9.com
