name: Validate 

on:
  push:
    branches:
      - main   # Specify the branch to trigger the workflow

jobs:
  pmd-code-analysis:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Install Java (PMD requires Java)
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Step 3: Download and install PMD
    - name: Install PMD
      run: |
        wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.47.0/pmd-bin-6.47.0.zip
        unzip pmd-bin-6.47.0.zip
        export PATH="$PATH:$(pwd)/pmd-bin-6.47.0/bin"

    # Step 4: Run PMD analysis on the Apex code
    - name: Run PMD on Apex Code
      run: |
        pmd -d force-app/main/default/classes/ -R apex-ruleset.xml -f text > pmd-report.txt
      continue-on-error: true

    # Step 5: Upload the PMD report as an artifact for review (updated version)
    - name: Upload PMD Report
      uses: actions/upload-artifact@v3
      with:
        name: pmd-report
        path: pmd-report.txt
