name: Validate

on:
  push:
    branches:
      - main   # Spécifiez la branche qui déclenche le workflow

jobs:
  pmd-code-analysis:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le dépôt
    - name: Vérifier le dépôt
      uses: actions/checkout@v2

    # Étape 2 : Installer Java (PMD nécessite Java)
    - name: Configurer JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Étape 3 : Télécharger et installer PMD
    - name: Installer PMD
      run: |
       # Télécharger PMD
        wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.47.0/pmd-bin-6.47.0.zip
        # Dézipper le fichier téléchargé
        unzip pmd-bin-6.47.0.zip
        # Ajouter le chemin PMD à la variable PATH
        echo "PMD_PATH=$(pwd)/pmd-bin-6.47.0/bin" >> $GITHUB_ENV
        echo "$PATH" # Optional: Print the PATH for debugging
    # Étape 4 : Exécuter l'analyse PMD
    - name: Exécuter PMD
      name: Run PMD on Apex Code
      run: |
            export PATH="$PATH:$(pwd)/pmd-bin-6.47.0/bin" # Ensure PATH is set here as well
            sh pmd -d force-app/main/default/apexRulesets/ -R MyRuleset.ruleset -f text > pmd-report.txt
      continue-on-error: true


    # Étape 5 : Télécharger le rapport PMD comme artefact
    - name: Télécharger le rapport PMD
      uses: actions/upload-artifact@v3
      with:
        name: pmd-report
        path: pmd-report.txt
