name: Salesforce SFDX Scanner Analysis

on:
  push:
    branches:
      - "main"

jobs:
  sfdx-scanner-analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Install Node.js using nvm (Ensure using a compatible version)
      - name: 'Install NodeJS'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install Salesforce CLI (SFDX)
      - name: 'Install Salesforce CLI'
        run: |
          npm install sfdx-cli --global

      # Step 4: Install SFDX Scanner plugin
      - name: Install SFDX Scanner
        run: |
          # Clean npm/yarn cache to avoid potential conflicts
          npm cache clean --force
          yarn cache clean
          # Install the plugin
          sfdx plugins:install @salesforce/sfdx-scanner

      # Step 5: Set environment variables for Salesforce CLI
      - name: Set Environment Variables
        run: |
          echo "SF_LAZY_LOAD_MODULES=true" >> $GITHUB_ENV
          echo "SF_AUTOUPDATE_DISABLE=true" >> $GITHUB_ENV
          echo "SF_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV

      # Step 6: Update Salesforce CLI
      - name: Update Salesforce CLI
        run: |
          sfdx update

      # Step 7: Run Salesforce Scanner with no bail flag
      - name: Run Salesforce Scanner
        run: |
          sfdx scanner:run --format sarif --target 'force-app/**/*.cls' \
            --category 'Security,Code Style,Performance,Best Practices,Design' \
            --outfile 'apexScanResults.sarif' --no-bail

      # Step 8: Upload SARIF file as an artifact
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: apexScanResults.sarif
